ssh-pubkey-login(User, ClientIP, ClientPort, KeyType, Fingerprint, Type)
 :- sshd-auth-pubkey(_, _, _, _, Ident, Pid, _,
                     User, ClientIP, ClientPort, KeyType, Fingerprint),
    sshd-user-child-pid(_, _, _, _, Ident, Pid, _,
                        ChildPid),
    sshd-session-start(_, _, _, _, _, ChildPid, _,
                       Type, _, _, _, _).

ssh-pubkey-login(User, ClientIP, ClientPort, KeyType, Fingerprint, Type)?
